version: '2'
services:
    integrationui-app:
        image: integrationui
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://integrationui-postgresql:5432/IntegrationUI
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 4321:4321
    integrationui-postgresql:
        extends:
            file: postgresql.yml
            service: integrationui-postgresql
