version: '2'
services:
    integrationui-postgresql:
        image: postgres:10.4
        # volumes:
        #     - ~/volumes/jhipster/IntegrationUI/postgresql/:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=IntegrationUI
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
